name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master

